# What is PyTorch?

It’s a Python based scientific computing package targeted at two sets of audiences:

* A replacement for numpy to use the power of GPUs
* a deep learning research platform that provides maximum flexibility and speed

![Tensors](resources/Basics/tensor_illustration.png)
PyTorch provides Tensors that can live either on the CPU or the GPU, and accelerate compute by a huge amount.

# Getting Started

## Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized:

In [2]:
torch.Tensor(5, 3)


    -0.0000      0.0000      0.0000
     0.0000         nan      0.0000
     0.0000      0.0000      0.0000
   195.2664      0.0000  12621.5498
 11404.0654      0.0000     -0.0000
[torch.FloatTensor of size 5x3]

Construct a randomly initialized matrix

In [3]:
torch.rand(5, 3)


 0.9556  0.1091  0.8947
 0.5467  0.5720  0.1813
 0.0873  0.7010  0.1173
 0.4674  0.9017  0.6847
 0.0838  0.8229  0.2531
[torch.FloatTensor of size 5x3]

Get its size

In [5]:
torch.rand(5, 3).size()

torch.Size([5, 3])

Note : torch.Size is in fact a _tuple_, so it supports the _same_ operations

In [6]:
torch.rand(5, 3).size()[0]

5

## Operations

###### There are multiple syntaxes for operations. 

Let’s see addition as an example

In [9]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

Addition: syntax 1

In [10]:
x + y


 1.4204  1.1257  0.6548
 0.4748  0.8995  1.3446
 1.0237  1.7146  1.7083
 0.9128  0.5709  1.5730
 0.8826  0.3322  1.6393
[torch.FloatTensor of size 5x3]

In [11]:
torch.add(x, y)


 1.4204  1.1257  0.6548
 0.4748  0.8995  1.3446
 1.0237  1.7146  1.7083
 0.9128  0.5709  1.5730
 0.8826  0.3322  1.6393
[torch.FloatTensor of size 5x3]

Addition: giving an output tensor

In [12]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
result


 1.4204  1.1257  0.6548
 0.4748  0.8995  1.3446
 1.0237  1.7146  1.7083
 0.9128  0.5709  1.5730
 0.8826  0.3322  1.6393
[torch.FloatTensor of size 5x3]

Addition: in-place

In [13]:
y.add_(x)
y


 1.4204  1.1257  0.6548
 0.4748  0.8995  1.3446
 1.0237  1.7146  1.7083
 0.9128  0.5709  1.5730
 0.8826  0.3322  1.6393
[torch.FloatTensor of size 5x3]

Note: Any operation that **mutates** a tensor in-place is post-fixed with a **_**

For example: 
```python
x.copy_(y)
```
and
```python
x.t_()
```
will change x.

##### You can use standard numpy-like indexing with all bells and whistles!

In [14]:
x[:, 1]


 0.7778
 0.3852
 0.8138
 0.3116
 0.0690
[torch.FloatTensor of size 5]

_Read later_:

**100+** Tensor operations, including _transposing, indexing, slicing, mathematical operations, linear algebra, random numbers_, etc are described [here](http://pytorch.org/docs/torch)

# Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

## Converting torch Tensor to numpy Array

In [15]:
a = torch.ones(5)
a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

In [16]:
b = a.numpy()
b

array([ 1.,  1.,  1.,  1.,  1.], dtype=float32)

See how the _numpy_ array changed in value?

In [17]:
a.add_(1)
a, b

(
  2
  2
  2
  2
  2
 [torch.FloatTensor of size 5],
 array([ 2.,  2.,  2.,  2.,  2.], dtype=float32))

## Converting numpy Array to torch Tensor

In [18]:
import numpy as np

In [19]:
a = np.ones(5)
a

array([ 1.,  1.,  1.,  1.,  1.])

In [20]:
b = torch.from_numpy(a)
b


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

See how changing the np array changed the torch Tensor **automatically**?

In [21]:
np.add(a, 1, out=a)
a, b

(array([ 2.,  2.,  2.,  2.,  2.]), 
  2
  2
  2
  2
  2
 [torch.DoubleTensor of size 5])

All the Tensors on the CPU except a _CharTensor_ support converting to NumPy and back.

# CUDA Tensors

Tensors can be moved onto GPU using the .cuda function.

In [24]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    
x + y


 2.1315  1.9035  1.0159
 0.8595  1.2847  2.0847
 1.8489  2.5285  2.7062
 1.0075  0.8825  2.5445
 1.6343  0.4012  2.6067
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]